name: duckstatsbomb-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - duckdb
  - grayskull
  - hatch
  - jupyterlab
  - pandas
  - pytest
  - python = 3.11
  - requests-cache
  - twine
  - pip
  - pip:
      - --editable .
