name: duckstatsbomb-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp
  - fsspec
  - grayskull
  - hatch
  - jupyterlab
  - pandas
  - pytest
  - twine
  - pip
  - pip:
      - --editable .
